# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            data stories
tagline:          'Romane Dagain'
description:      "Let's talk about digital storytelling."
url:              http://romanedgn.github.io
baseurl:          /

author:
  name:           'Romane Dagain'
  url:            https://twitter.com/romanedagain

paginate:         5

# Custom vars
version:          2.1.0


